tbp:
  # 腾讯云账户 secretId
  secretId: AKIDE3nKrGYnsofN9ufIjw78u2CD2c6WjjTe
  # 腾讯云账户 secretKey
  secretKey: HMBlFYmngswqZSOD1nMlxvpZ7TdbXJuG
  # 域名接入，就近地域接入域名为 tbp.tencentcloudapi.com，推荐使用就近地域接入域名。根据调用接口时客户端所在位置，会自动解析到最近的某个具体地域的服务器。
  endpoint: tbp.tencentcloudapi.com
  # 机器人标识，用于定义抽象机器人。
  botId: fc9424d7-1555-49fb-b072-df47e97bc7c4
  # 机器人版本，取值 "dev"调试版本 或 "release"线上版本
  botEnv: release

# 是否在bot注册完成后自动启动他们。
# 默认为true
#simbot:
#  auto-start-bots: true
#
## 自定义配置bot资源文件的扫描路径。
## 默认为 classpath:simbot-bots/*.bot*
#  bot-configuration-resources[0]: classpath:*.bot*
#
##配置监听的QQ号，多个QQ用逗号分割
#MonitorQQ: 3374097824

